---
driver:
  name: vagrant # vagrant
  #binary: /usr/local/bin/docker
  #use_sudo: false
  #privileged: true

# This works, but is way slower than using docker
#driver:
#  name: vagrant

platforms:
  - name: ubuntu-16.04
#  - name: ubuntu-17.04
#  - name: centos-7.4

provisioner:
  name: salt_solo
  salt_version: latest
  salt_install: bootstrap
  salt_bootstrap_options: -p git
  dependencies:
    - name: postgres
      path: ../postgres-formula
  log_level: info
  require_chef: false
  salt_file_root: /srv/salt
  salt_pillar_root: /srv/pillar
  formula: sonarqube
  state_top:
    base:
      '*':
        - postgres.python
        - postgres.server
        - postgres.client
        - postgres.manage
        - sonarqube
  pillars-from-files:
    sonarqube.sls: pillar.example
    postgres.sls: tests/pillar.postgres
  pillars:
    top.sls:
      base:
        '*':
          - postgres
          - sonarqube

suites:
  - name: default

verifier:
  name: shell
  remote_exec: false
  command: pytest --junit-xml=./junit-full.xml -v tests/
